// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BvJqWNcdlm0iDXabdErU-HaIG8E5qsg',
    appId: '1:601275560805:web:22a7daf7132071bd3fe78c',
    messagingSenderId: '601275560805',
    projectId: 'uber-5049e',
    authDomain: 'uber-5049e.firebaseapp.com',
    storageBucket: 'uber-5049e.appspot.com',
    measurementId: 'G-PZTBMWT3Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVVcxO9e-xPvXMYLMmc2PDGiavDUroVRA',
    appId: '1:601275560805:android:223e053235f79c753fe78c',
    messagingSenderId: '601275560805',
    projectId: 'uber-5049e',
    storageBucket: 'uber-5049e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2RBimY2weRoWa_Ntk-SIfJC2rXdzU7A',
    appId: '1:601275560805:ios:7fe9ba8eb795a5aa3fe78c',
    messagingSenderId: '601275560805',
    projectId: 'uber-5049e',
    storageBucket: 'uber-5049e.appspot.com',
    iosBundleId: 'com.example.uberProjecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2RBimY2weRoWa_Ntk-SIfJC2rXdzU7A',
    appId: '1:601275560805:ios:7fe9ba8eb795a5aa3fe78c',
    messagingSenderId: '601275560805',
    projectId: 'uber-5049e',
    storageBucket: 'uber-5049e.appspot.com',
    iosBundleId: 'com.example.uberProjecto',
  );
}
